// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqtsVPZ_fRcocwyuRAhKhzeoipelI502s',
    appId: '1:773736711004:web:3c2a831c3b0c54c2ca7799',
    messagingSenderId: '773736711004',
    projectId: 'main3-c7c1b',
    authDomain: 'main3-c7c1b.firebaseapp.com',
    storageBucket: 'main3-c7c1b.appspot.com',
    measurementId: 'G-HRGJZ8MJ9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSw4NmQQ7dw9OJU5HxmB2uDZwZjyWUmfY',
    appId: '1:773736711004:android:916cf1ed49fc38d7ca7799',
    messagingSenderId: '773736711004',
    projectId: 'main3-c7c1b',
    storageBucket: 'main3-c7c1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlEqqoPQORrtpcos1VKaDfvo0niBzY6qk',
    appId: '1:773736711004:ios:cf07c2d1ca45140eca7799',
    messagingSenderId: '773736711004',
    projectId: 'main3-c7c1b',
    storageBucket: 'main3-c7c1b.appspot.com',
    iosBundleId: 'com.example.mainproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlEqqoPQORrtpcos1VKaDfvo0niBzY6qk',
    appId: '1:773736711004:ios:bb7c245f736c8201ca7799',
    messagingSenderId: '773736711004',
    projectId: 'main3-c7c1b',
    storageBucket: 'main3-c7c1b.appspot.com',
    iosBundleId: 'com.example.mainproject.RunnerTests',
  );
}
